### ISSUE TITLE
Spatial axis trait

### ISSUE THREAD

**Issue by Cody-G** [JuliaImages/ImageAxes.jl#11]
I'm not sure if I've understood this correctly, but it seems that currently the low-level function `filter_space_axes` selects any axes that do not have the time axis trait.  Could this cause a problem when an image consists of space, time, and other axis types?  Would it be worthwhile to implement a proper spatial axis trait?

**Comment by timholy** [comment]
At the moment I've been assuming that all axes are space or time---if you want it to be "interpreted," color shouldn't be an axis in the new scheme because it should be encoded as a `Colorant` (the motivating reason for ImageCore having so many tools for easily "casting" an array to and from color types). Do you have a good example of an axis type that's neither spatial or temporal that's useful in image processing?

One problem with defining a spatial axis trait is that, because the names are more likely to be diverse, it  requires more participation from users to "register" the axis names. I'd almost prefer to have it be that one registers an axis as _not_ being spatial, and spatial-by-default is assumed otherwise.

This conversation reminds me that `ImagineFormat` should be migrated in much the same what that I changed NRRD.

**Comment by Cody-G** [comment]
Looking to science for an example, an imaging experiment with multiple trials might be considered to have a trial axis.  And while trials are acquired at different times, it may not always be fair to call that dimension temporal.  Or more generally one might want to define axes for different contexts, for example observing the same biological sample under different dosages of a drug.

I'm not sure how often there will be significant advantages (either performance-wise or conceptually) in grouping such samplings into one image versus different images.  Does the design of the new `Images.jl` favor one way or the other?

If we did want to have a spatial trait, I wonder if it could be simplified by defining an `is_length_unit` trait for each unit within Unitful.  I'm guessing that's not the whole solution, because we probably don't want to require that spatial units be defined for all images -- though maybe `pixel` could serve as a default spatial unit?

**Comment by timholy** [comment]
Great example. You may note that using [`atindex`](https://github.com/JuliaArrays/AxisArrays.jl) with multiple indexes will result in a `time_rep` and a `time_sub` axis. Would it be unreasonable to consider both of them temporal? It would just mean adding a couple extra definitions [like this one](https://github.com/JuliaImages/ImageAxes.jl/blob/047c670e9602e5e52f3fc4f78d815d55250998df/src/ImageAxes.jl#L29).

**Comment by Cody-G** [comment]
`atindex` does seem pretty powerful.  Maybe it is okay to consider them both temporal.  I just want to make sure I understand the best way to handle both multiple trials and multiple conditions.  Would it be smart to create a different `AxisArray` for each condition, and then use `atindex` to label trials within a condition?  I don't see a way to handle it with a single `AxisArray` (which I don't think is necessarily a bad thing).

**Comment by timholy** [comment]
Interesting question. You're right that there doesn't seem to be a way to define multiple conditions. Especially if different conditions have different numbers of trials, it seems that the `AxisArray` framework isn't well-suited to handle all of those cases with a single AA, so indeed having multiple `view`s of the overarching dataset seems like a good way to go.

**Comment by Cody-G** [comment]
That sounds good for my purposes, just wanted to make sure I wasn't missing something.  Thanks!
